import React from 'react';
// import { makeStyles } from '@mui/material/styles';
import { Container, Typography } from '@mui/material';

// const useStyles = makeStyles((theme) => ({
//     root: {
//         padding: theme.spacing(3, 2),
//     },
// }));

function About() {
    // const classes = useStyles();

    return (
        <Container maxWidth="sm">
            <Typography variant="h5" component="h2" gutterBottom>
                About the DoD Sexual Assault Prevention and Response Office Oversight Tool
            </Typography>
            <Typography variant="body1" gutterBottom>
                This online tool was created for the DoD Sexual Assault Prevention and Response Office Oversight team to streamline the evaluation and auditing process of requirements for commands under their purview. The tool allows commands to submit supporting documentation remotely, making the process more efficient and convenient.
            </Typography>
            <Typography variant="body1" gutterBottom>
                The tool was developed with Material Design principles in mind, ensuring a user-friendly and visually appealing experience. The goal is to make it easy for commands to understand the requirements and provide the necessary documentation for evaluation and auditing.
            </Typography>
            <Typography variant="body1">
                The DoD Sexual Assault Prevention and Response Office Oversight team is committed to improving the support and resources available to those affected by sexual assault. By utilizing this tool, they can more effectively evaluate and audit requirements to ensure that all commands are meeting the necessary standards and providing the best possible support.
            </Typography>
        </Container>
    );
};

// This was all generated by chatGPT. Pretty impressive.
// TODO: Update to actually be accurate

export default About;
